---

- name: Checkout fzf
  git:
    repo=https://github.com/junegunn/fzf.git
    dest=/home/{{ user }}/.fzf

- name: Install fzf
  script: /home/{{ user }}/.fzf/install --all
  args:
    creates:
      - /home/{{ user }}/.fzf.zsh
      - /home/{{ user }}/.fzf/bin/fzf
  environment:
    BASH_SOURCE: /home/{{ user }}/.fzf/install

- name: Copy fzf script
  copy:
    src=fzf.zsh
    dest=/home/{{ user }}/.oh-my-zsh/custom
